services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PROJECT_NAME=RoslaTech-Dev
      - JWT_KEY=
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRY_MINUTES=30
      - DB_URL=sqlite:///database/main.db
      - ORIGINS=[]
    volumes:
      - ./database:/src/database
      - ./backend/app:/src/app
    ports:
      - 8000:8000
    networks:
      dev:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    ports:
      - 8080:80
    networks:
      dev:

networks:
  dev:
    driver: bridge