services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PROJECT_NAME=RoslaTech-Dev
      - JWT_KEY=
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRY_MINUTES=30
      - DB_URL=sqlite:///development.db
      - ORIGINS=[]
    volumes:
      - ./database/development.db:/src/development.db
      - ./backend/app:/src/app
    ports:
      - 8000:8000
    networks:
      dev:


networks:
  dev:
    driver: bridge